vcom -work work ./../../src/pkgGlobal/Global-p.vhd
vcom -work work ./../../src/unitsForSim/Oscillator-e.vhd
vcom -work work ./../../src/unitsForSim/Oscillator-Bhv-a.vhd
vcom -work work ./../../src/unitsForSim/PwrOnReset-e.vhd
vcom -work work ./../../src/unitsForSim/PwrOnReset-Bhv-a.vhd
vcom -work work ./../../src/unitStrobeGen/src/StrobeGen-e.vhd
vcom -work work ./../../src/unitStrobeGen/src/StrobeGen-Rtl-a.vhd
vcom -work work ./RoundSensor-e.vhd
vcom -work work ./RoundSensor-Rtl-a.vhd
vcom -work work ./tbRoundSensor.vhd
