# TCL File Generated by Component Editor 15.0
# Fri Jan 29 22:51:25 CET 2016
# DO NOT MODIFY


# 
# Motor_Control "DC Motor Control" v1.0
# Lukas Rappel 2016.01.29.22:51:25
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module Motor_Control
# 
set_module_property DESCRIPTION ""
set_module_property NAME Motor_Control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SocGhostCar
set_module_property AUTHOR "Lukas Rappel"
set_module_property DISPLAY_NAME "DC Motor Control"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Motor_Control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Motor_Control.vhd VHDL PATH Motor_Control.vhd TOP_LEVEL_FILE
add_fileset_file Global-p.vhd VHDL PATH ../src/pkgGlobal/Global-p.vhd
add_fileset_file PwmGenPack-p.vhd VHDL PATH ../src/pkgPwmGenPack/src/PwmGenPack-p.vhd
add_fileset_file PwmGen-Rtl-a.vhd VHDL PATH ../src/unitPwmGen/src/PwmGen-Rtl-a.vhd
add_fileset_file PwmGen-e.vhd VHDL PATH ../src/unitPwmGen/src/PwmGen-e.vhd
add_fileset_file PwmGenCtrlpath-Rtl-a.vhd VHDL PATH ../src/unitPwmGenCtrlpath/src/PwmGenCtrlpath-Rtl-a.vhd
add_fileset_file PwmGenCtrlpath-e.vhd VHDL PATH ../src/unitPwmGenCtrlpath/src/PwmGenCtrlpath-e.vhd
add_fileset_file PwmGenDatapath-e.vhd VHDL PATH ../src/unitPwmGenDatapath/src/PwmGenDatapath-e.vhd
add_fileset_file PwmGenDatapath-Rtl-a.vhd VHDL PATH ../src/unitPwmGenDatapath/src/PwmGenDatapath-Rtl-a.vhd
add_fileset_file StrobeGen-e.vhd VHDL PATH ../src/unitStrobeGen/src/StrobeGen-e.vhd
add_fileset_file StrobeGen-Rtl-a.vhd VHDL PATH ../src/unitStrobeGen/src/StrobeGen-Rtl-a.vhd
add_fileset_file WheelEncoderTimer-Rtl-a.vhd VHDL PATH ./WheelEncoderTimer/WheelEncoderTimer-Rtl-a.vhd
add_fileset_file WheelEncoderTimer-e.vhd VHDL PATH ./WheelEncoderTimer/WheelEncoderTimer-e.vhd
add_fileset_file RoundSensor-Rtl-a.vhd VHDL PATH ./RoundSensor/RoundSensor-Rtl-a.vhd
add_fileset_file RoundSensor-e.vhd VHDL PATH ./RoundSensor/RoundSensor-e.vhd


# 
# documentation links
# 
add_documentation_link "Data Sheet" file:///D:/7.2015WS/PRO/svn/trunk/04_software/fpga/Motor_control/doc/Motor_control.pdf


# 
# parameters
# 
add_parameter gQSYS_ClkFrequency_Hz NATURAL 50000000 ""
set_parameter_property gQSYS_ClkFrequency_Hz DEFAULT_VALUE 50000000
set_parameter_property gQSYS_ClkFrequency_Hz DISPLAY_NAME gQSYS_ClkFrequency_Hz
set_parameter_property gQSYS_ClkFrequency_Hz WIDTH ""
set_parameter_property gQSYS_ClkFrequency_Hz TYPE NATURAL
set_parameter_property gQSYS_ClkFrequency_Hz UNITS None
set_parameter_property gQSYS_ClkFrequency_Hz ALLOWED_RANGES 0:2147483647
set_parameter_property gQSYS_ClkFrequency_Hz DESCRIPTION "System clock frequency"
set_parameter_property gQSYS_ClkFrequency_Hz HDL_PARAMETER true

add_parameter gQSYS_MotorFrequency_Hz NATURAL 1000 "Hz"
set_parameter_property gQSYS_MotorFrequency_Hz DEFAULT_VALUE 1000
set_parameter_property gQSYS_MotorFrequency_Hz DISPLAY_NAME gQSYS_MotorFrequency_Hz
set_parameter_property gQSYS_MotorFrequency_Hz WIDTH ""
set_parameter_property gQSYS_MotorFrequency_Hz TYPE NATURAL
set_parameter_property gQSYS_MotorFrequency_Hz UNITS None
set_parameter_property gQSYS_MotorFrequency_Hz ALLOWED_RANGES 500:4000
set_parameter_property gQSYS_MotorFrequency_Hz DESCRIPTION "Motor switching frequency"
set_parameter_property gQSYS_MotorFrequency_Hz HDL_PARAMETER true

add_parameter gQSYS_TimerResolution_us NATURAL 1 "us"
set_parameter_property gQSYS_TimerResolution_us DEFAULT_VALUE 1
set_parameter_property gQSYS_TimerResolution_us DISPLAY_NAME gQSYS_TimerResolution_us
set_parameter_property gQSYS_TimerResolution_us WIDTH ""
set_parameter_property gQSYS_TimerResolution_us TYPE NATURAL
set_parameter_property gQSYS_TimerResolution_us UNITS None
set_parameter_property gQSYS_TimerResolution_us ALLOWED_RANGES 1:100
set_parameter_property gQSYS_TimerResolution_us DESCRIPTION "speed signal sampling time"
set_parameter_property gQSYS_TimerResolution_us HDL_PARAMETER true

add_parameter gQSYS_TimeOut_ms NATURAL 100 ""
set_parameter_property gQSYS_TimeOut_ms DEFAULT_VALUE 100
set_parameter_property gQSYS_TimeOut_ms DISPLAY_NAME gQSYS_TimeOut_ms
set_parameter_property gQSYS_TimeOut_ms WIDTH ""
set_parameter_property gQSYS_TimeOut_ms TYPE NATURAL
set_parameter_property gQSYS_TimeOut_ms UNITS None
set_parameter_property gQSYS_TimeOut_ms ALLOWED_RANGES 0:1000
set_parameter_property gQSYS_TimeOut_ms DESCRIPTION "speed signal time out (zero speed)"
set_parameter_property gQSYS_TimeOut_ms HDL_PARAMETER true

add_parameter gQSYS_ValidSamples NATURAL 20 ""
set_parameter_property gQSYS_ValidSamples DEFAULT_VALUE 20
set_parameter_property gQSYS_ValidSamples DISPLAY_NAME gQSYS_ValidSamples
set_parameter_property gQSYS_ValidSamples WIDTH ""
set_parameter_property gQSYS_ValidSamples TYPE NATURAL
set_parameter_property gQSYS_ValidSamples UNITS None
set_parameter_property gQSYS_ValidSamples ALLOWED_RANGES 1:100
set_parameter_property gQSYS_ValidSamples DESCRIPTION "valid samples to detect signal change"
set_parameter_property gQSYS_ValidSamples HDL_PARAMETER true

# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 3
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point external
# 
add_interface external conduit end
set_interface_property external associatedClock clock
set_interface_property external associatedReset reset
set_interface_property external ENABLED true
set_interface_property external EXPORT_OF ""
set_interface_property external PORT_NAME_MAP ""
set_interface_property external CMSIS_SVD_VARIABLES ""
set_interface_property external SVD_ADDRESS_GROUP ""

add_interface_port external PWM_CTRL pwm_outuput Output 1
add_interface_port external ACTIVATE enablesignal Output 1
add_interface_port external SENSOR sensorsignal Input 1
add_interface_port external ROUND roundsignal Input 1

# +-----------------------------------
# | Device tree generation
# |
set_module_assignment embeddedsw.dts.vendor "FHOOE"
set_module_assignment embeddedsw.dts.compatible "dev,motor-control"
set_module_assignment embeddedsw.dts.group "motorcontrol"
# |
# +-----------------------------------



# 
# display items
# 

