# TCL File Generated by Component Editor 15.0
# Fri Dec 25 21:51:30 CET 2015
# DO NOT MODIFY


# 
# CarreraProtocolDecoder "Carrera Digital: Protocol Decoder" v1.0
# Lukas Rappel 2015.12.25.21:51:30
# Carrera Digital Decoder
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module CarreraProtocolDecoder
# 
set_module_property DESCRIPTION "Carrera Digital Decoder"
set_module_property NAME CarreraProtocolDecoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SocGhostCar
set_module_property AUTHOR "Lukas Rappel"
set_module_property DISPLAY_NAME "Carrera Digital: Protocol Decoder"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CarreraProtocolDecoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Global-p.vhd VHDL PATH ../src/pkgGlobal/Global-p.vhd
add_fileset_file CarreraProtocol-e.vhd VHDL PATH CarreraProtocol-e.vhd
add_fileset_file CarreraProtocol-Rtl-a.vhd VHDL PATH CarreraProtocol-Rtl-a.vhd
add_fileset_file CarreraProtocolDecoder.vhd VHDL PATH CarreraProtocolDecoder.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL CarreraProtocolDecoder
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tbCarreraProtocol.vhd VHDL PATH tbCarreraProtocol.vhd


# 
# documentation links
# 
add_documentation_link Manual file:///D:/7.2015WS/PRO1/svn/trunk/04_software/fpga/CarreraProtocol/doc/CarreraProtocol.pdf
add_documentation_link Slotbaer http://www.slotbaer.de/index.php/carrera-digital-124-132/12-d132-d124-daten-protokoll


# 
# parameters
# 
add_parameter ParamClkFrequency NATURAL 50000000 "system clock rate"
set_parameter_property ParamClkFrequency DEFAULT_VALUE 50000000
set_parameter_property ParamClkFrequency DISPLAY_NAME ClkFrequency
set_parameter_property ParamClkFrequency WIDTH ""
set_parameter_property ParamClkFrequency TYPE NATURAL
set_parameter_property ParamClkFrequency UNITS None
set_parameter_property ParamClkFrequency ALLOWED_RANGES 0:100000000
set_parameter_property ParamClkFrequency DESCRIPTION "system clock rate"
set_parameter_property ParamClkFrequency HDL_PARAMETER true
add_parameter ParamBaudrate NATURAL 10000 "carrera digital baudrate"
set_parameter_property ParamBaudrate DEFAULT_VALUE 10000
set_parameter_property ParamBaudrate DISPLAY_NAME Baudrate
set_parameter_property ParamBaudrate TYPE NATURAL
set_parameter_property ParamBaudrate UNITS None
set_parameter_property ParamBaudrate ALLOWED_RANGES 9800:12000
set_parameter_property ParamBaudrate DESCRIPTION "carrera digital baudrate"
set_parameter_property ParamBaudrate HDL_PARAMETER true
add_parameter ParamDataWidth NATURAL 16 "max. telegram data width"
set_parameter_property ParamDataWidth DEFAULT_VALUE 16
set_parameter_property ParamDataWidth DISPLAY_NAME DataWidth
set_parameter_property ParamDataWidth TYPE NATURAL
set_parameter_property ParamDataWidth UNITS None
set_parameter_property ParamDataWidth ALLOWED_RANGES 8:16
set_parameter_property ParamDataWidth DESCRIPTION "max. telegram data width"
set_parameter_property ParamDataWidth HDL_PARAMETER true
add_parameter ParamIDWidth NATURAL 32 "ID width"
set_parameter_property ParamIDWidth DEFAULT_VALUE 32
set_parameter_property ParamIDWidth DISPLAY_NAME IDWidth
set_parameter_property ParamIDWidth TYPE NATURAL
set_parameter_property ParamIDWidth UNITS None
set_parameter_property ParamIDWidth ALLOWED_RANGES 16:32
set_parameter_property ParamIDWidth DESCRIPTION "ID width"
set_parameter_property ParamIDWidth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 2
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end RailSignal RailSignal Input 1

# +-----------------------------------
# | Device tree generation
# |
set_module_assignment embeddedsw.dts.vendor "FHOOE"
set_module_assignment embeddedsw.dts.compatible "dev,carrera-decoder"
set_module_assignment embeddedsw.dts.group "carrera"
# |
# +-----------------------------------

