// megafunction wizard: %ALTFP_CONVERT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTFP_CONVERT 

// ============================================================
// File Name: tofixed.v
// Megafunction Name(s):
// 			ALTFP_CONVERT
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 16.0.0 Build 211 04/27/2016 SJ Standard Edition
// ************************************************************


//Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Altera and sold by Altera or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//altfp_convert DEVICE_FAMILY="Cyclone V" OPERATION="FLOAT2FIXED" ROUNDING="TO_NEAREST" WIDTH_DATA=64 WIDTH_EXP_INPUT=11 WIDTH_EXP_OUTPUT=8 WIDTH_INT=12 WIDTH_MAN_INPUT=52 WIDTH_MAN_OUTPUT=23 WIDTH_RESULT=64 aclr clock dataa result
//VERSION_BEGIN 16.0 cbx_altbarrel_shift 2016:04:27:18:05:34:SJ cbx_altera_syncram_nd_impl 2016:04:27:18:05:34:SJ cbx_altfp_convert 2016:04:27:18:05:34:SJ cbx_altpriority_encoder 2016:04:27:18:05:34:SJ cbx_altsyncram 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_abs 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_lpm_divide 2016:04:27:18:05:34:SJ cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_stratixiii 2016:04:27:18:05:34:SJ cbx_stratixv 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altbarrel_shift DEVICE_FAMILY="Cyclone V" PIPELINE=2 SHIFTDIR="VARIABLE" SHIFTTYPE="LOGICAL" WIDTH=115 WIDTHDIST=7 aclr clk_en clock data direction distance result
//VERSION_BEGIN 16.0 cbx_altbarrel_shift 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ  VERSION_END

//synthesis_resources = reg 235 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  tofixed_altbarrel_shift
	( 
	aclr,
	clk_en,
	clock,
	data,
	direction,
	distance,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clk_en;
	input   clock;
	input   [114:0]  data;
	input   direction;
	input   [6:0]  distance;
	output   [114:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clk_en;
	tri0   clock;
	tri0   direction;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[1:0]	dir_pipe;
	reg	[114:0]	sbit_piper1d;
	reg	[114:0]	sbit_piper2d;
	reg	sel_pipec4r1d;
	reg	sel_pipec5r1d;
	reg	sel_pipec6r1d;
	wire  [7:0]  dir_w;
	wire  direction_w;
	wire  [63:0]  pad_w;
	wire  [919:0]  sbit_w;
	wire  [6:0]  sel_w;
	wire  [804:0]  smux_w;

	// synopsys translate_off
	initial
		dir_pipe = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) dir_pipe <= 2'b0;
		else if  (clk_en == 1'b1)   dir_pipe <= {dir_w[6], dir_w[3]};
	// synopsys translate_off
	initial
		sbit_piper1d = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sbit_piper1d <= 115'b0;
		else if  (clk_en == 1'b1)   sbit_piper1d <= smux_w[459:345];
	// synopsys translate_off
	initial
		sbit_piper2d = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sbit_piper2d <= 115'b0;
		else if  (clk_en == 1'b1)   sbit_piper2d <= smux_w[804:690];
	// synopsys translate_off
	initial
		sel_pipec4r1d = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sel_pipec4r1d <= 1'b0;
		else if  (clk_en == 1'b1)   sel_pipec4r1d <= distance[4];
	// synopsys translate_off
	initial
		sel_pipec5r1d = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sel_pipec5r1d <= 1'b0;
		else if  (clk_en == 1'b1)   sel_pipec5r1d <= distance[5];
	// synopsys translate_off
	initial
		sel_pipec6r1d = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sel_pipec6r1d <= 1'b0;
		else if  (clk_en == 1'b1)   sel_pipec6r1d <= distance[6];
	assign
		dir_w = {dir_pipe[1], dir_w[5:4], dir_pipe[0], dir_w[2:0], direction_w},
		direction_w = direction,
		pad_w = {64{1'b0}},
		result = sbit_w[919:805],
		sbit_w = {sbit_piper2d, smux_w[689:460], sbit_piper1d, smux_w[344:0], data},
		sel_w = {sel_pipec6r1d, sel_pipec5r1d, sel_pipec4r1d, distance[3:0]},
		smux_w = {((({115{(sel_w[6] & (~ dir_w[6]))}} & {sbit_w[740:690], pad_w[63:0]}) | ({115{(sel_w[6] & dir_w[6])}} & {pad_w[63:0], sbit_w[804:754]})) | ({115{(~ sel_w[6])}} & sbit_w[804:690])), ((({115{(sel_w[5] & (~ dir_w[5]))}} & {sbit_w[657:575], pad_w[31:0]}) | ({115{(sel_w[5] & dir_w[5])}} & {pad_w[31:0], sbit_w[689:607]})) | ({115{(~ sel_w[5])}} & sbit_w[689:575])), ((({115{(sel_w[4] & (~ dir_w[4]))}} & {sbit_w[558:460], pad_w[15:0]}) | ({115{(sel_w[4] & dir_w[4])}} & {pad_w[15:0], sbit_w[574:476]})) | ({115{(~ sel_w[4])}} & sbit_w[574:460])), ((({115{(sel_w[3] & (~ dir_w[3]))}} & {sbit_w[451:345], pad_w[7:0]}) | ({115{(sel_w[3] & dir_w[3])}} & {pad_w[7:0], sbit_w[459:353]})) | ({115{(~ sel_w[3])}} & sbit_w[459:345])), ((({115{(sel_w[2] & (~ dir_w[2]))}} & {sbit_w[340:230], pad_w[3:0]}) | ({115{(sel_w[2] & dir_w[2])}} & {pad_w[3:0], sbit_w[344:234]})) | ({115{(~ sel_w[2])}} & sbit_w[344:230])), ((({115{(sel_w[1] & (~ dir_w[1]))}} & {sbit_w[227:115], pad_w[1:0]}) | ({115{(sel_w[1] & dir_w[1])}} & {pad_w[1:0], sbit_w[229:117]})) | ({115{(~ sel_w[1])}} & sbit_w[229:115])), ((({115{(sel_w[0] & (~ dir_w[0]))}} & {sbit_w[113:0], pad_w[0]}) | ({115{(sel_w[0] & dir_w[0])}} & {pad_w[0], sbit_w[114:1]})) | ({115{(~ sel_w[0])}} & sbit_w[114:0]))};
endmodule //tofixed_altbarrel_shift


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="ADD" LPM_WIDTH=63 ONE_INPUT_IS_CONSTANT="YES" cout dataa datab result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="ADD" LPM_WIDTH=7 ONE_INPUT_IS_CONSTANT="YES" dataa datab result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="ADD" LPM_WIDTH=31 ONE_INPUT_IS_CONSTANT="YES" cout dataa datab result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="ADD" LPM_WIDTH=32 ONE_INPUT_IS_CONSTANT="YES" dataa datab result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="SUB" LPM_WIDTH=7 ONE_INPUT_IS_CONSTANT="YES" dataa datab result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="SUB" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=11 ONE_INPUT_IS_CONSTANT="YES" dataa datab overflow result
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=11 aeb dataa datab
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  tofixed_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [10:0]  dataa;
	input   [10:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [10:0]  dataa;
	tri0   [10:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [29:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[10], dataa[10], datab[9], dataa[9], datab[8], dataa[8], datab[7], dataa[7], datab[6], dataa[6], datab[5], dataa[5], datab[4], dataa[4], datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], (data_wire[28] ^ data_wire[29]), ((data_wire[24] ^ data_wire[25]) | (data_wire[26] ^ data_wire[27])), ((data_wire[20] ^ data_wire[21]) | (data_wire[22] ^ data_wire[23])), ((data_wire[16] ^ data_wire[17]) | (data_wire[18] ^ data_wire[19])), ((data_wire[12] ^ data_wire[13]) | (data_wire[14] ^ data_wire[15])), ((data_wire[8] ^ data_wire[9]) | (data_wire[10] ^ data_wire[11])), (data_wire[6] | data_wire[7]), (((data_wire[2] | data_wire[3]) | data_wire[4]) | data_wire[5])},
		eq_wire = aeb_result_wire;
endmodule //tofixed_cmpr


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=11 aeb agb dataa datab
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_REPRESENTATION="SIGNED" LPM_WIDTH=7 agb dataa datab
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = lut 173 reg 531 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  tofixed_altfp_convert
	( 
	aclr,
	clock,
	dataa,
	result) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   [63:0]  dataa;
	output   [63:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [114:0]   wire_altbarrel_shift2_result;
	reg	[6:0]	added_power2_reg;
	reg	barrel_direction_negative_reg;
	reg	below_lower_limit3_reg1;
	reg	below_lower_limit3_reg2;
	reg	below_lower_limit3_reg3;
	reg	below_lower_limit3_reg4;
	reg	border_lower_limit_reg1;
	reg	border_lower_limit_reg2;
	reg	border_lower_limit_reg3;
	reg	border_lower_limit_reg4;
	reg	[63:0]	dataa_reg;
	reg	equal_upper_limit_reg1;
	reg	equal_upper_limit_reg2;
	reg	equal_upper_limit_reg3;
	reg	exceed_upper_limit_reg1;
	reg	exceed_upper_limit_reg2;
	reg	exceed_upper_limit_reg3;
	reg	exceed_upper_limit_reg4;
	reg	exp_and_reg1;
	reg	exp_and_reg2;
	reg	exp_and_reg3;
	reg	exp_and_reg4;
	reg	exp_or_reg1;
	reg	exp_or_reg2;
	reg	exp_or_reg3;
	reg	exp_or_reg4;
	reg	int_or1_reg1;
	reg	int_or2_reg1;
	reg	int_or_reg2;
	reg	int_or_reg3;
	reg	[63:0]	integer_result_reg;
	reg	[62:0]	integer_rounded_reg;
	reg	man_or1_reg1;
	reg	man_or2_reg1;
	reg	man_or_reg2;
	reg	man_or_reg3;
	reg	man_or_reg4;
	reg	[51:0]	mantissa_input_reg;
	reg	max_shift_exceeder_reg;
	reg	max_shift_reg;
	reg	[6:0]	power2_value_reg;
	reg	sign_input_reg1;
	reg	sign_input_reg2;
	reg	sign_input_reg3;
	reg	sign_input_reg4;
	wire	[63:0]	wire_add_1_adder_result_int;
	wire	wire_add_1_adder_cout;
	wire	[62:0]	wire_add_1_adder_dataa;
	wire	[62:0]	wire_add_1_adder_datab;
	wire	[62:0]	wire_add_1_adder_result;
	wire	[6:0]	wire_add_sub1_dataa;
	wire	[6:0]	wire_add_sub1_datab;
	wire	[6:0]	wire_add_sub1_result;
	wire	[31:0]	wire_add_sub3_result_int;
	wire	wire_add_sub3_cout;
	wire	[30:0]	wire_add_sub3_dataa;
	wire	[30:0]	wire_add_sub3_datab;
	wire	[30:0]	wire_add_sub3_result;
	wire	[31:0]	wire_add_sub4_dataa;
	wire	[31:0]	wire_add_sub4_datab;
	wire	[31:0]	wire_add_sub4_result;
	wire	[6:0]	wire_barrel_direction_invert_dataa;
	wire	[6:0]	wire_barrel_direction_invert_datab;
	wire	[6:0]	wire_barrel_direction_invert_result;
	wire	[11:0]	wire_power2_value_result_int;
	wire	[10:0]	wire_power2_value_dataa;
	wire	[10:0]	wire_power2_value_datab;
	wire	wire_power2_value_overflow;
	wire	[10:0]	wire_power2_value_result;
	wire  wire_below_lower_limit1_aeb;
	wire  wire_below_lower_limit2_aeb;
	reg	wire_exceed_upper_limit_aeb_int;
	reg	wire_exceed_upper_limit_agb_int;
	wire	wire_exceed_upper_limit_aeb;
	wire	wire_exceed_upper_limit_agb;
	wire	[10:0]	wire_exceed_upper_limit_dataa;
	wire	[10:0]	wire_exceed_upper_limit_datab;
	reg	wire_max_shift_compare_agb_int;
	wire	wire_max_shift_compare_agb;
	wire	[6:0]	wire_max_shift_compare_dataa;
	wire	[6:0]	wire_max_shift_compare_datab;
	wire	[6:0]	wire_max_shift_compare_dataa_int;
	wire	[6:0]	wire_max_shift_compare_datab_int;
	wire  add_1_cout_w;
	wire  add_1_w;
	wire  [63:0]  all_zeroes_w;
	wire  barrel_direction_negative;
	wire  [114:0]  barrel_mantissa_input;
	wire  [61:0]  barrel_zero_padding_w;
	wire  below_limit_exceeders;
	wire  [63:0]  below_limit_integer;
	wire  [10:0]  below_lower_limit3_anding;
	wire  [3:0]  below_lower_limit3_oring;
	wire  below_lower_limit3_w;
	wire  [10:0]  bias_value_less_1_w;
	wire clk_en;
	wire  [10:0]  const_bias_value_add_width_res_w;
	wire  denormal_input_w;
	wire  equal_upper_limit_w;
	wire  exceed_limit_exceeders;
	wire  [63:0]  exceed_limit_integer;
	wire  exceed_upper_limit_w;
	wire  [10:0]  exp_and;
	wire  exp_and_w;
	wire  [10:0]  exp_bus;
	wire  [10:0]  exp_or;
	wire  exp_or_w;
	wire  [10:0]  exponent_input;
	wire  guard_bit_w;
	wire  [52:0]  implied_mantissa_input;
	wire  infinity_input_w;
	wire  [63:0]  infinity_value_w;
	wire  int_or1_w;
	wire  int_or2_w;
	wire  [63:0]  integer_output;
	wire  [62:0]  integer_post_round;
	wire  [62:0]  integer_pre_round;
	wire  [63:0]  integer_result;
	wire  [62:0]  integer_rounded;
	wire  [62:0]  integer_rounded_tmp;
	wire  [62:0]  integer_tmp_output;
	wire  [30:0]  inv_add_1_adder1_w;
	wire  [31:0]  inv_add_1_adder2_w;
	wire  [62:0]  inv_integer;
	wire  [114:0]  lbarrel_shift_result_w;
	wire  [62:0]  lbarrel_shift_w;
	wire  lowest_integer_selector;
	wire  [62:0]  lowest_integer_value;
	wire  [25:0]  man_bus1;
	wire  [25:0]  man_bus2;
	wire  [25:0]  man_or1;
	wire  man_or1_w;
	wire  [25:0]  man_or2;
	wire  man_or2_w;
	wire  man_or_w;
	wire  [51:0]  mantissa_input;
	wire  max_shift_reg_w;
	wire  [6:0]  max_shift_w;
	wire  more_than_max_shift_w;
	wire  nan_input_w;
	wire  [63:0]  neg_infi_w;
	wire  [10:0]  padded_exponent_input;
	wire  [63:0]  pos_infi_w;
	wire  power2_value_overflow_w;
	wire  [6:0]  power2_value_w;
	wire  [63:0]  result_w;
	wire  round_bit_w;
	wire  [10:0]  shift_value_w;
	wire  sign_input;
	wire  sign_input_w;
	wire  [62:0]  signed_integer;
	wire  sticky_bit_w;
	wire  [50:0]  sticky_bus;
	wire  [50:0]  sticky_or;
	wire  [62:0]  unsigned_integer;
	wire  upper_limit_w;
	wire  zero_input_w;

	tofixed_altbarrel_shift   altbarrel_shift2
	( 
	.aclr(aclr),
	.clk_en(clk_en),
	.clock(clock),
	.data(barrel_mantissa_input),
	.direction(barrel_direction_negative),
	.distance((({7{barrel_direction_negative}} & wire_barrel_direction_invert_result) | ({7{(~ barrel_direction_negative)}} & power2_value_reg))),
	.result(wire_altbarrel_shift2_result));
	// synopsys translate_off
	initial
		added_power2_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) added_power2_reg <= 7'b0;
		else if  (clk_en == 1'b1)   added_power2_reg <= wire_add_sub1_result;
	// synopsys translate_off
	initial
		barrel_direction_negative_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) barrel_direction_negative_reg <= 1'b0;
		else if  (clk_en == 1'b1)   barrel_direction_negative_reg <= wire_power2_value_result[10];
	// synopsys translate_off
	initial
		below_lower_limit3_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) below_lower_limit3_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   below_lower_limit3_reg1 <= below_lower_limit3_w;
	// synopsys translate_off
	initial
		below_lower_limit3_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) below_lower_limit3_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   below_lower_limit3_reg2 <= below_lower_limit3_reg1;
	// synopsys translate_off
	initial
		below_lower_limit3_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) below_lower_limit3_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   below_lower_limit3_reg3 <= below_lower_limit3_reg2;
	// synopsys translate_off
	initial
		below_lower_limit3_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) below_lower_limit3_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   below_lower_limit3_reg4 <= below_lower_limit3_reg3;
	// synopsys translate_off
	initial
		border_lower_limit_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) border_lower_limit_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   border_lower_limit_reg1 <= wire_below_lower_limit2_aeb;
	// synopsys translate_off
	initial
		border_lower_limit_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) border_lower_limit_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   border_lower_limit_reg2 <= border_lower_limit_reg1;
	// synopsys translate_off
	initial
		border_lower_limit_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) border_lower_limit_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   border_lower_limit_reg3 <= border_lower_limit_reg2;
	// synopsys translate_off
	initial
		border_lower_limit_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) border_lower_limit_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   border_lower_limit_reg4 <= border_lower_limit_reg3;
	// synopsys translate_off
	initial
		dataa_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) dataa_reg <= 64'b0;
		else if  (clk_en == 1'b1)   dataa_reg <= dataa;
	// synopsys translate_off
	initial
		equal_upper_limit_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) equal_upper_limit_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   equal_upper_limit_reg1 <= equal_upper_limit_w;
	// synopsys translate_off
	initial
		equal_upper_limit_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) equal_upper_limit_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   equal_upper_limit_reg2 <= equal_upper_limit_reg1;
	// synopsys translate_off
	initial
		equal_upper_limit_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) equal_upper_limit_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   equal_upper_limit_reg3 <= equal_upper_limit_reg2;
	// synopsys translate_off
	initial
		exceed_upper_limit_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exceed_upper_limit_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   exceed_upper_limit_reg1 <= exceed_upper_limit_w;
	// synopsys translate_off
	initial
		exceed_upper_limit_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exceed_upper_limit_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   exceed_upper_limit_reg2 <= exceed_upper_limit_reg1;
	// synopsys translate_off
	initial
		exceed_upper_limit_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exceed_upper_limit_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   exceed_upper_limit_reg3 <= exceed_upper_limit_reg2;
	// synopsys translate_off
	initial
		exceed_upper_limit_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exceed_upper_limit_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   exceed_upper_limit_reg4 <= upper_limit_w;
	// synopsys translate_off
	initial
		exp_and_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_and_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_and_reg1 <= exp_and_w;
	// synopsys translate_off
	initial
		exp_and_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_and_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_and_reg2 <= exp_and_reg1;
	// synopsys translate_off
	initial
		exp_and_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_and_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_and_reg3 <= exp_and_reg2;
	// synopsys translate_off
	initial
		exp_and_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_and_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_and_reg4 <= exp_and_reg3;
	// synopsys translate_off
	initial
		exp_or_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_or_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_or_reg1 <= exp_or_w;
	// synopsys translate_off
	initial
		exp_or_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_or_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_or_reg2 <= exp_or_reg1;
	// synopsys translate_off
	initial
		exp_or_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_or_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_or_reg3 <= exp_or_reg2;
	// synopsys translate_off
	initial
		exp_or_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) exp_or_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   exp_or_reg4 <= exp_or_reg3;
	// synopsys translate_off
	initial
		int_or1_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) int_or1_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   int_or1_reg1 <= int_or1_w;
	// synopsys translate_off
	initial
		int_or2_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) int_or2_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   int_or2_reg1 <= int_or2_w;
	// synopsys translate_off
	initial
		int_or_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) int_or_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   int_or_reg2 <= (int_or1_reg1 | int_or2_reg1);
	// synopsys translate_off
	initial
		int_or_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) int_or_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   int_or_reg3 <= int_or_reg2;
	// synopsys translate_off
	initial
		integer_result_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) integer_result_reg <= 64'b0;
		else if  (clk_en == 1'b1)   integer_result_reg <= integer_result;
	// synopsys translate_off
	initial
		integer_rounded_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) integer_rounded_reg <= 63'b0;
		else if  (clk_en == 1'b1)   integer_rounded_reg <= integer_rounded;
	// synopsys translate_off
	initial
		man_or1_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_or1_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   man_or1_reg1 <= man_or1_w;
	// synopsys translate_off
	initial
		man_or2_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_or2_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   man_or2_reg1 <= man_or2_w;
	// synopsys translate_off
	initial
		man_or_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_or_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   man_or_reg2 <= man_or_w;
	// synopsys translate_off
	initial
		man_or_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_or_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   man_or_reg3 <= man_or_reg2;
	// synopsys translate_off
	initial
		man_or_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) man_or_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   man_or_reg4 <= man_or_reg3;
	// synopsys translate_off
	initial
		mantissa_input_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) mantissa_input_reg <= 52'b0;
		else if  (clk_en == 1'b1)   mantissa_input_reg <= mantissa_input;
	// synopsys translate_off
	initial
		max_shift_exceeder_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) max_shift_exceeder_reg <= 1'b0;
		else if  (clk_en == 1'b1)   max_shift_exceeder_reg <= more_than_max_shift_w;
	// synopsys translate_off
	initial
		max_shift_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) max_shift_reg <= 1'b0;
		else if  (clk_en == 1'b1)   max_shift_reg <= wire_max_shift_compare_agb;
	// synopsys translate_off
	initial
		power2_value_reg = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) power2_value_reg <= 7'b0;
		else if  (clk_en == 1'b1)   power2_value_reg <= power2_value_w;
	// synopsys translate_off
	initial
		sign_input_reg1 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_input_reg1 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_input_reg1 <= sign_input;
	// synopsys translate_off
	initial
		sign_input_reg2 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_input_reg2 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_input_reg2 <= sign_input_reg1;
	// synopsys translate_off
	initial
		sign_input_reg3 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_input_reg3 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_input_reg3 <= sign_input_reg2;
	// synopsys translate_off
	initial
		sign_input_reg4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) sign_input_reg4 <= 1'b0;
		else if  (clk_en == 1'b1)   sign_input_reg4 <= sign_input_reg3;
	assign
		wire_add_1_adder_result_int = wire_add_1_adder_dataa + wire_add_1_adder_datab;
	assign
		wire_add_1_adder_result = wire_add_1_adder_result_int[62:0],
		wire_add_1_adder_cout = wire_add_1_adder_result_int[63:63];
	assign
		wire_add_1_adder_dataa = integer_pre_round,
		wire_add_1_adder_datab = 63'b000000000000000000000000000000000000000000000000000000000000001;
	assign
		wire_add_sub1_result = wire_add_sub1_dataa + wire_add_sub1_datab;
	assign
		wire_add_sub1_dataa = power2_value_reg,
		wire_add_sub1_datab = 7'b0000001;
	assign
		wire_add_sub3_result_int = wire_add_sub3_dataa + wire_add_sub3_datab;
	assign
		wire_add_sub3_result = wire_add_sub3_result_int[30:0],
		wire_add_sub3_cout = wire_add_sub3_result_int[31:31];
	assign
		wire_add_sub3_dataa = inv_integer[30:0],
		wire_add_sub3_datab = 31'b0000000000000000000000000000001;
	assign
		wire_add_sub4_result = wire_add_sub4_dataa + wire_add_sub4_datab;
	assign
		wire_add_sub4_dataa = inv_integer[62:31],
		wire_add_sub4_datab = 32'b00000000000000000000000000000001;
	assign
		wire_barrel_direction_invert_result = wire_barrel_direction_invert_dataa - wire_barrel_direction_invert_datab;
	assign
		wire_barrel_direction_invert_dataa = 7'b0000000,
		wire_barrel_direction_invert_datab = power2_value_reg;
	assign
		wire_power2_value_result_int = wire_power2_value_dataa - wire_power2_value_datab;
	assign
		wire_power2_value_result = wire_power2_value_result_int[10:0],
		wire_power2_value_overflow = wire_power2_value_result_int[11:11];
	assign
		wire_power2_value_dataa = exponent_input,
		wire_power2_value_datab = shift_value_w;
	tofixed_cmpr   below_lower_limit1
	( 
	.aeb(wire_below_lower_limit1_aeb),
	.dataa(exponent_input),
	.datab(bias_value_less_1_w));
	tofixed_cmpr   below_lower_limit2
	( 
	.aeb(wire_below_lower_limit2_aeb),
	.dataa(exponent_input),
	.datab(shift_value_w));
	always @(wire_exceed_upper_limit_dataa or wire_exceed_upper_limit_datab)
	begin
		if (wire_exceed_upper_limit_dataa == wire_exceed_upper_limit_datab) 
			begin
				wire_exceed_upper_limit_aeb_int = 1'b1;
			end
		else
			begin
				wire_exceed_upper_limit_aeb_int = 1'b0;
			end
		if (wire_exceed_upper_limit_dataa > wire_exceed_upper_limit_datab) 
			begin
				wire_exceed_upper_limit_agb_int = 1'b1;
			end
		else
			begin
				wire_exceed_upper_limit_agb_int = 1'b0;
			end
	end
	assign
		wire_exceed_upper_limit_aeb = wire_exceed_upper_limit_aeb_int,
		wire_exceed_upper_limit_agb = wire_exceed_upper_limit_agb_int;
	assign
		wire_exceed_upper_limit_dataa = padded_exponent_input,
		wire_exceed_upper_limit_datab = const_bias_value_add_width_res_w;
	assign
		wire_max_shift_compare_dataa_int = {~wire_max_shift_compare_dataa[6:6], wire_max_shift_compare_dataa[5:0]},
		wire_max_shift_compare_datab_int = {~wire_max_shift_compare_datab[6:6], wire_max_shift_compare_datab[5:0]};
	always @(wire_max_shift_compare_dataa_int or wire_max_shift_compare_datab_int)
	begin
		if (wire_max_shift_compare_dataa_int > wire_max_shift_compare_datab_int) 
			begin
				wire_max_shift_compare_agb_int = 1'b1;
			end
		else
			begin
				wire_max_shift_compare_agb_int = 1'b0;
			end
	end
	assign
		wire_max_shift_compare_agb = wire_max_shift_compare_agb_int;
	assign
		wire_max_shift_compare_dataa = added_power2_reg,
		wire_max_shift_compare_datab = max_shift_w;
	assign
		add_1_cout_w = ((wire_add_1_adder_cout & add_1_w) & (~ sign_input_reg3)),
		add_1_w = (round_bit_w & (guard_bit_w | sticky_bit_w)),
		all_zeroes_w = {1'b0, {63{1'b0}}},
		barrel_direction_negative = barrel_direction_negative_reg,
		barrel_mantissa_input = {barrel_zero_padding_w, implied_mantissa_input},
		barrel_zero_padding_w = {62{1'b0}},
		below_limit_exceeders = ((((denormal_input_w | zero_input_w) | nan_input_w) | below_lower_limit3_reg4) & (~ border_lower_limit_reg4)),
		below_limit_integer = (({64{(~ below_limit_exceeders)}} & integer_output) | ({64{below_limit_exceeders}} & all_zeroes_w)),
		below_lower_limit3_anding = {(below_lower_limit3_anding[9] & wire_power2_value_result[10]), (below_lower_limit3_anding[8] & wire_power2_value_result[9]), (below_lower_limit3_anding[7] & wire_power2_value_result[8]), (below_lower_limit3_anding[6] & wire_power2_value_result[7]), (below_lower_limit3_anding[5] & wire_power2_value_result[6]), (below_lower_limit3_anding[4] & wire_power2_value_result[5]), (below_lower_limit3_anding[3] & wire_power2_value_result[4]), (below_lower_limit3_anding[2] & wire_power2_value_result[3]), (below_lower_limit3_anding[1] & wire_power2_value_result[2]), (below_lower_limit3_anding[0] & wire_power2_value_result[1]), wire_power2_value_result[0]},
		below_lower_limit3_oring = {(below_lower_limit3_oring[2] | wire_power2_value_result[10]), (below_lower_limit3_oring[1] | wire_power2_value_result[9]), (below_lower_limit3_oring[0] | wire_power2_value_result[8]), wire_power2_value_result[7]},
		below_lower_limit3_w = (((wire_power2_value_result[10] & below_lower_limit3_oring[3]) | power2_value_overflow_w) & (~ below_lower_limit3_anding[10])),
		bias_value_less_1_w = 11'b01111111110,
		clk_en = 1'b1,
		const_bias_value_add_width_res_w = 11'b10000001010,
		denormal_input_w = ((~ exp_or_reg4) & man_or_reg4),
		equal_upper_limit_w = wire_exceed_upper_limit_aeb,
		exceed_limit_exceeders = (((infinity_input_w | max_shift_exceeder_reg) | exceed_upper_limit_reg4) & (~ nan_input_w)),
		exceed_limit_integer = (({64{(~ exceed_limit_exceeders)}} & below_limit_integer) | ({64{exceed_limit_exceeders}} & infinity_value_w)),
		exceed_upper_limit_w = wire_exceed_upper_limit_agb,
		exp_and = {(exp_and[9] & exp_bus[10]), (exp_and[8] & exp_bus[9]), (exp_and[7] & exp_bus[8]), (exp_and[6] & exp_bus[7]), (exp_and[5] & exp_bus[6]), (exp_and[4] & exp_bus[5]), (exp_and[3] & exp_bus[4]), (exp_and[2] & exp_bus[3]), (exp_and[1] & exp_bus[2]), (exp_and[0] & exp_bus[1]), exp_bus[0]},
		exp_and_w = exp_and[10],
		exp_bus = exponent_input,
		exp_or = {(exp_or[9] | exp_bus[10]), (exp_or[8] | exp_bus[9]), (exp_or[7] | exp_bus[8]), (exp_or[6] | exp_bus[7]), (exp_or[5] | exp_bus[6]), (exp_or[4] | exp_bus[5]), (exp_or[3] | exp_bus[4]), (exp_or[2] | exp_bus[3]), (exp_or[1] | exp_bus[2]), (exp_or[0] | exp_bus[1]), exp_bus[0]},
		exp_or_w = exp_or[10],
		exponent_input = dataa_reg[62:52],
		guard_bit_w = wire_altbarrel_shift2_result[52],
		implied_mantissa_input = {1'b1, mantissa_input_reg},
		infinity_input_w = (exp_and_reg4 & (~ man_or_reg4)),
		infinity_value_w = (({64{(~ sign_input_w)}} & pos_infi_w) | ({64{sign_input_w}} & neg_infi_w)),
		int_or1_w = man_or2[0],
		int_or2_w = man_or1[0],
		integer_output = {sign_input_w, integer_tmp_output},
		integer_post_round = wire_add_1_adder_result,
		integer_pre_round = lbarrel_shift_w,
		integer_result = exceed_limit_integer,
		integer_rounded = (({63{(~ lowest_integer_selector)}} & integer_rounded_tmp) | ({63{lowest_integer_selector}} & lowest_integer_value)),
		integer_rounded_tmp = (({63{(~ add_1_w)}} & integer_pre_round) | ({63{add_1_w}} & integer_post_round)),
		integer_tmp_output = (({63{(~ sign_input_w)}} & unsigned_integer) | ({63{sign_input_w}} & signed_integer)),
		inv_add_1_adder1_w = wire_add_sub3_result,
		inv_add_1_adder2_w = (({32{(~ wire_add_sub3_cout)}} & inv_integer[62:31]) | ({32{wire_add_sub3_cout}} & wire_add_sub4_result)),
		inv_integer = (~ integer_rounded_reg),
		lbarrel_shift_result_w = wire_altbarrel_shift2_result,
		lbarrel_shift_w = lbarrel_shift_result_w[114:52],
		lowest_integer_selector = 1'b0,
		lowest_integer_value = {barrel_zero_padding_w, 1'b1},
		man_bus1 = mantissa_input[25:0],
		man_bus2 = mantissa_input[51:26],
		man_or1 = {man_bus1[25], (man_or1[25] | man_bus1[24]), (man_or1[24] | man_bus1[23]), (man_or1[23] | man_bus1[22]), (man_or1[22] | man_bus1[21]), (man_or1[21] | man_bus1[20]), (man_or1[20] | man_bus1[19]), (man_or1[19] | man_bus1[18]), (man_or1[18] | man_bus1[17]), (man_or1[17] | man_bus1[16]), (man_or1[16] | man_bus1[15]), (man_or1[15] | man_bus1[14]), (man_or1[14] | man_bus1[13]), (man_or1[13] | man_bus1[12]), (man_or1[12] | man_bus1[11]), (man_or1[11] | man_bus1[10]), (man_or1[10] | man_bus1[9]), (man_or1[9] | man_bus1[8]), (man_or1[8] | man_bus1[7]), (man_or1[7] | man_bus1[6]), (man_or1[6] | man_bus1[5]), (man_or1[5] | man_bus1[4]), (man_or1[4] | man_bus1[3]), (man_or1[3] | man_bus1[2]), (man_or1[2] | man_bus1[1]), (man_or1[1] | man_bus1[0])},
		man_or1_w = man_or1[0],
		man_or2 = {man_bus2[25], (man_or2[25] | man_bus2[24]), (man_or2[24] | man_bus2[23]), (man_or2[23] | man_bus2[22]), (man_or2[22] | man_bus2[21]), (man_or2[21] | man_bus2[20]), (man_or2[20] | man_bus2[19]), (man_or2[19] | man_bus2[18]), (man_or2[18] | man_bus2[17]), (man_or2[17] | man_bus2[16]), (man_or2[16] | man_bus2[15]), (man_or2[15] | man_bus2[14]), (man_or2[14] | man_bus2[13]), (man_or2[13] | man_bus2[12]), (man_or2[12] | man_bus2[11]), (man_or2[11] | man_bus2[10]), (man_or2[10] | man_bus2[9]), (man_or2[9] | man_bus2[8]), (man_or2[8] | man_bus2[7]), (man_or2[7] | man_bus2[6]), (man_or2[6] | man_bus2[5]), (man_or2[5] | man_bus2[4]), (man_or2[4] | man_bus2[3]), (man_or2[3] | man_bus2[2]), (man_or2[2] | man_bus2[1]), (man_or2[1] | man_bus2[0])},
		man_or2_w = man_or2[0],
		man_or_w = (man_or1_reg1 | man_or2_reg1),
		mantissa_input = dataa_reg[51:0],
		max_shift_reg_w = max_shift_reg,
		max_shift_w = 7'b0001010,
		more_than_max_shift_w = (max_shift_reg_w & add_1_cout_w),
		nan_input_w = (exp_and_reg4 & man_or_reg4),
		neg_infi_w = {1'b1, {63{1'b0}}},
		padded_exponent_input = exponent_input,
		pos_infi_w = {1'b0, {63{1'b1}}},
		power2_value_overflow_w = wire_power2_value_overflow,
		power2_value_w = wire_power2_value_result[6:0],
		result = result_w,
		result_w = integer_result_reg,
		round_bit_w = wire_altbarrel_shift2_result[51],
		shift_value_w = 11'b01111001011,
		sign_input = dataa_reg[63],
		sign_input_w = sign_input_reg4,
		signed_integer = {inv_add_1_adder2_w, inv_add_1_adder1_w},
		sticky_bit_w = sticky_or[50],
		sticky_bus = wire_altbarrel_shift2_result[50:0],
		sticky_or = {(sticky_or[49] | sticky_bus[50]), (sticky_or[48] | sticky_bus[49]), (sticky_or[47] | sticky_bus[48]), (sticky_or[46] | sticky_bus[47]), (sticky_or[45] | sticky_bus[46]), (sticky_or[44] | sticky_bus[45]), (sticky_or[43] | sticky_bus[44]), (sticky_or[42] | sticky_bus[43]), (sticky_or[41] | sticky_bus[42]), (sticky_or[40] | sticky_bus[41]), (sticky_or[39] | sticky_bus[40]), (sticky_or[38] | sticky_bus[39]), (sticky_or[37] | sticky_bus[38]), (sticky_or[36] | sticky_bus[37]), (sticky_or[35] | sticky_bus[36]), (sticky_or[34] | sticky_bus[35]), (sticky_or[33] | sticky_bus[34]), (sticky_or[32] | sticky_bus[33]), (sticky_or[31] | sticky_bus[32]), (sticky_or[30] | sticky_bus[31]), (sticky_or[29] | sticky_bus[30]), (sticky_or[28] | sticky_bus[29]), (sticky_or[27] | sticky_bus[28]), (sticky_or[26] | sticky_bus[27]), (sticky_or[25] | sticky_bus[26]), (sticky_or[24] | sticky_bus[25]), (sticky_or[23] | sticky_bus[24]), (sticky_or[22] | sticky_bus[23]), (sticky_or[21] | sticky_bus[22]), (sticky_or[20] | sticky_bus[21]), (sticky_or[19] | sticky_bus[20]), (sticky_or[18] | sticky_bus[19]), (sticky_or[17] | sticky_bus[18]), (sticky_or[16] | sticky_bus[17]), (sticky_or[15] | sticky_bus[16]), (sticky_or[14] | sticky_bus[15]), (sticky_or[13] | sticky_bus[14]), (sticky_or[12] | sticky_bus[13]), (sticky_or[11] | sticky_bus[12]), (sticky_or[10] | sticky_bus[11]), (sticky_or[9] | sticky_bus[10]), (sticky_or[8] | sticky_bus[9]), (sticky_or[7] | sticky_bus[8]), (sticky_or[6] | sticky_bus[7]), (sticky_or[5] | sticky_bus[6]), (sticky_or[4] | sticky_bus[5]), (sticky_or[3] | sticky_bus[4]), (sticky_or[2] | sticky_bus[3]), (sticky_or[1] | sticky_bus[2]), (sticky_or[0] | sticky_bus[1]), sticky_bus[0]},
		unsigned_integer = integer_rounded_reg,
		upper_limit_w = (((~ sign_input_reg3) & (exceed_upper_limit_reg3 | equal_upper_limit_reg3)) | (sign_input_reg3 & (exceed_upper_limit_reg3 | (equal_upper_limit_reg3 & (int_or_reg3 | add_1_w))))),
		zero_input_w = ((~ exp_or_reg4) & (~ man_or_reg4));
endmodule //tofixed_altfp_convert
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module tofixed (
	aclr,
	clock,
	dataa,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	  clock;
	input	[63:0]  dataa;
	output	[63:0]  result;

	wire [63:0] sub_wire0;
	wire [63:0] result = sub_wire0[63:0];

	tofixed_altfp_convert	tofixed_altfp_convert_component (
				.aclr (aclr),
				.clock (clock),
				.dataa (dataa),
				.result (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: LPM_HINT STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altfp_convert"
// Retrieval info: CONSTANT: OPERATION STRING "FLOAT2FIXED"
// Retrieval info: CONSTANT: ROUNDING STRING "TO_NEAREST"
// Retrieval info: CONSTANT: WIDTH_DATA NUMERIC "64"
// Retrieval info: CONSTANT: WIDTH_EXP_INPUT NUMERIC "11"
// Retrieval info: CONSTANT: WIDTH_EXP_OUTPUT NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_INT NUMERIC "12"
// Retrieval info: CONSTANT: WIDTH_MAN_INPUT NUMERIC "52"
// Retrieval info: CONSTANT: WIDTH_MAN_OUTPUT NUMERIC "23"
// Retrieval info: CONSTANT: WIDTH_RESULT NUMERIC "64"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT NODEFVAL "aclr"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: USED_PORT: dataa 0 0 64 0 INPUT NODEFVAL "dataa[63..0]"
// Retrieval info: CONNECT: @dataa 0 0 64 0 dataa 0 0 64 0
// Retrieval info: USED_PORT: result 0 0 64 0 OUTPUT NODEFVAL "result[63..0]"
// Retrieval info: CONNECT: result 0 0 64 0 @result 0 0 64 0
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed.vhd TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed.qip TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed.bsf TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed_inst.vhd TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed.inc TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL tofixed.cmp TRUE TRUE
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX NUMERIC "1"
// Retrieval info: LIB_FILE: lpm
